version: '3.4'

services:
  lesson:
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - DOCKER_ENV=true